/**
 * OOPSBannerApp UC2 - Banner Dsipaly Application(Use case 3)
 * 
 * This class Demonstrate s the creation of a visual banner displaying the word "OOPS"
 * using ASCII art composed of astriecs(*) and spaces.The banner is printed to the 
 * concole using individual print statements for each line , creating a decorative 
 * text effect 
 * 
 * <p> the banner is generated by printing predefined string parteens line by line
 * were each line contributres to forming the letters O , O , P , S in a stylish format
 * this extends a basic use story by adding visuual presentation to a simple message format.
 * <p>
 * 
 * @author Developer
 * @version 3.0
 */
// Extend the Use case UC2 touse string.join() method to create each line of the OOPS banner case
// Use System.out.println() to print each line of the 00PS banner to create
// drawbacks of using the + operator for string concatenation which essentially creates
// multiple intermediate String objects in memory leading to inefficiency.
public class OOPSbannerUC3 {
    // Main method to run the banner display
    // Use System.out.println() to print each line of the 00PS banner to create 
    // the visual effect for the message "00PS". Construct each line using 
    // String.join() method for better readability and efficiency.
    // Each line corresponds to a row in the banner for the letters 0, 0, P, S.
    public static void main(String[] args) {
        System.out.println(String.join("   ***   " , "   ***   " , "******   " , "   ***** "));
        System.out.println(String.join(" **   ** " , " **   ** " , "**    ** " , " **      "));
        System.out.println(String.join("**     **" , "**     **" , "**     **" , "**       "));
        System.out.println(String.join("**     **" , "**     **" , "**    ** " , " **      "));
        System.out.println(String.join("**     **" , "**     **" , "******   " , "   ***   "));
        System.out.println(String.join("**     **" , "**     **" , "**       " , "      ** "));
        System.out.println(String.join("**     **" , "**     **" , "**       " , "       **"));
        System.out.println(String.join(" **   ** " , " **   ** " , "**       " , "      ** "));
        System.out.println(String.join("   ***   " , "   ***   " , "**       " , "******   "));
    }
}