/**
 * OOPSBannerApp UC2 - Banner Dsipaly Application
 * 
 * This class Demonstrate s the creation of a visual banner displaying the word "OOPS"
 * using ASCII art composed of astriecs(*) and spaces.The banner is printed to the 
 * concole using individual print statements for each line , creating a decorative 
 * text effect 
 * 
 * <p> the banner is generated by printing predefined string parteens line by line
 * were each line contributres to forming the letters O , O , P , S in a stylish format
 * this extends a basic use story by adding visuual presentation to a simple message format.
 * <p>
 * 
 * @author Developer
 * @version 2
 */
// Extend the User Story 1 to display the message "OOPS" in a banner format
// using the charecters formed by spaces and asterisks (*) to  create a visual
// effect for each letter in the message. use print statements for each line
//insted of a loop
public class OOPSbannerUC2 {
    // Main method to run the banner display 
    // print each line of the OOPS banner to create the visual effect for the 
    //message "OOPS".construct each line using string contenation
    //each line is correspoonds to a row of the banner  for the letters O , O , P , S.
    //using individuialprint statements for each line.
    public static void main(String[] args) {
        System.out.println("   ***   " + " " + "   ***   " + " " + "******   " + " " + "   ***** ");
        System.out.println(" **   ** " + " " + " **   ** " + " " + "**    ** " + " " + " **      ");
        System.out.println("**     **" + " " + "**     **" + " " + "**     **" + " " + "**       ");
        System.out.println("**     **" + " " + "**     **" + " " + "**    ** " + " " + " **      ");
        System.out.println("**     **" + " " + "**     **" + " " + "******   " + " " + "   ***   ");
        System.out.println("**     **" + " " + "**     **" + " " + "**       " + " " + "      ** ");
        System.out.println("**     **" + " " + "**     **" + " " + "**       " + " " + "       **");
        System.out.println(" **   ** " + " " + " **   ** " + " " + "**       " + " " + "      ** ");
        System.out.println("   ***   " + " " + "   ***   " + " " + "**       " + " " + "******   ");
    }
}
